viewer: fix getLatestHeigth called when widget is disposed Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError NoSuchMethodError: The getter 'itemLeadingEdge' was called on null. Receiver: null Tried calling: itemLeadingEdge. Error thrown Instance of 'ErrorDescription'. _ViewerPageState._getLatestHeight (_ViewerPageState.java:1674) _ViewerPageState.initState.<fn> (initState.java:116) ChangeNotifier.notifyListeners (ChangeNotifier.java:308) ValueNotifier.value= (ValueNotifier.java:412) _ScrollablePositionedListState._updatePositions (_ScrollablePositionedListState.java:556) ChangeNotifier.notifyListeners (ChangeNotifier.java:308) ValueNotifier.value= (ValueNotifier.java:412) _PositionedListState._schedulePositionNotificationUpdate.<fn> (_schedulePositionNotificationUpdate.java:344) SchedulerBinding._invokeFrameCallback (SchedulerBinding.java:1143) SchedulerBinding.handleDrawFrame (SchedulerBinding.java:1088) SchedulerBinding._handleDrawFrame (SchedulerBinding.java:996)